#!/bin/bash
#
# Startup script for the Jenkins Continuous Integration server
#
# chkconfig: - 85 15
# description: Jenkins Continous Integration server
# pidfile: $JENKINS_HOME/jenkins.pid

# Set jenkins environment
JENKINS_USER="lfscidev"
HTTP_PORT="8090"
HTTP_LISTEN_ADDRESS="0.0.0.0"
JVM_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1536M -Xmn128M -Xms1024M -Xmx1536M -Djava.io.tmpdir=/var/tmp"
JENKINS_HOME="/var/fpwork/lfscidev/jenkins"
LFS_CI_ROOT="/home/lfscidev/lfs-ci"
LFS_CI_CONFIG_FILE="${LFS_CI_ROOT}/etc/development.cfg"
PID_FILE="$JENKINS_HOME/jenkins.pid"
LOG_FILE="$JENKINS_HOME/jenkins.log"

function ecw () {
    su - ${JENKINS_USER} -c "export JENKINS_HOME=/var/fpwork/lfscidev/jenkins; export LFS_CI_ROOT=${LFS_CI_ROOT}; export LFS_CI_CONFIG_FILE=${LFS_CI_CONFIG_FILE}; $1"
    return $?
}

function getPid () {
    echo "$(ps aux | grep jenkins.war | grep -v grep | awk '{print $2}')"
}

ecw "touch $PID_FILE"

# Let's start the fun
case "$1" in
  start)
        # Start daemon.
        echo -n "Starting Jenkins: "
        ecw "java $JVM_OPTS -jar $JENKINS_HOME/jenkins.war --httpListenAddress=$HTTP_LISTEN_ADDRESS --httpPort=$HTTP_PORT > $LOG_FILE 2>&1 &"
        RETVAL=$?

        sleep 2
        if [ $RETVAL -eq 0 ]; then
          PID="$(getPid)"
          [[ ! "$PID" ]] && echo "failed" && exit 1

          ecw  "echo -n $PID > $PID_FILE"
          echo "success"
        else
          [[ $? -ne 0 ]] && echo "failed" && exit 1
        fi
        ;;
  stop)
        # Stop daemon.
        echo -n "Shutting down Jenkins: "
        
        PID="$(getPid)"
        if [ "$PID" ]; then
          ecw "kill $PID"
          RETVAL=$?

           if [ $RETVAL -eq 0 ]; then
             ecw  "rm -f $PID_FILE"
             echo "success"
           else
             echo "failed"
            exit 1
           fi
        else
          echo "not needed, no Jenkins instance is running"
          exit 0
        fi
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        if [ "$(getPid)" ]; then
          echo "Jenkins is running"
        else
          echo "Jenkins is not running"
        fi
        ;;
  *)
        echo "Usage: $0 {start <LFS_CI_ROOT=/path/to/lfs-ci>|stop|restart|status}"
        exit 1
esac

exit 0
