#!/bin/bash

source ${LFS_CI_ROOT}/lib/common.sh
source ${LFS_CI_ROOT}/lib/logging.sh
source ${LFS_CI_ROOT}/lib/jenkins.sh

jobsName=$1

if existsJenkinsJob ${jobsName} ; then
    enableJob ${jobsName}
else 
    error "job ${jobsName} does not exist"
    exit 1
fi

exit 0
