#!/bin/bash

source ${LFS_CI_ROOT}/lib/common.sh
source ${LFS_CI_ROOT}/lib/logging.sh
source ${LFS_CI_ROOT}/lib/jenkins.sh


JOB_NAME=$1
JOB_XML_FILE=$2
BRANCH=$3
SVN_SERVER=$(getConfig lfsSourceRepos)

PATTERN1="<description><\/description>"
REVISION=$(svn log --verbose --stop-on-copy $SVN_SERVER/os/$BRANCH | grep -E "(from .*trunk:)" | cut -d'(' -f2 | cut -d':' -f2 | sed s'/)//')
PATTERN2="<description>Branched from trunk revision $REVISION<\/description>"

sed -i -e "0,/${PATTERN1}/s/${PATTERN1}/${PATTERN2}/" $JOB_XML_FILE

