#!/bin/bash
# Select a random host for ssh connection (out of the list).
# We had the problem in the past, that sshd on a single host
# is rejecting ssh connection due to the limit of ssh connections
# per minute. See also MaxStartups in sshd_config.
# So we select a random host from the list below to avoid the problem.
#
# this script should be configured as ProxyCommand in ssh-config.
# e.g. 
# Host linsee_server_ulm
#      ProxyCommand  ~/bin/sshrandom linsee_server_ulm

case $1 in
    linsee_server_ulm)
        declare -a hosts=( ciyellow.emea.nsn-net.net \
                           cired.emea.nsn-net.net \
                           cigreen.emea.nsn-net.net \
                           ciblue.emea.nsn-net.net \
                           ciblack.emea.nsn-net.net \
                           ciwhite.emea.nsn-net.net \
                           cipink.emea.nsn-net.net \
                           civiolet.emea.nsn-net.net \
                           ciorange.emea.nsn-net.net \
                           cibrown.emea.nsn-net.net )
    ;;
    linsee_server_ulm_lrc)
       declare -a hosts=( ullteb03.emea.nsn-net.net \
                          ullteb07.emea.nsn-net.net \
                          civiolet.emea.nsn-net.net )
    ;;
esac
hostCount=${#hosts[@]}
index=$(( RANDOM % ${hostCount} ))
selectedHost=${hosts[index]}
exec /usr/bin/nc ${selectedHost} 22
